#ifndef _GLOBALVARIABLES_H_
#define _GLOBALVARIABLES_H_

#define WINDOW_TITLE "Snake"

#define SCREEN_WIDTH 852
#define SCREEN_HEIGHT 480
#define SCREEN_BPP 32

#define AUDIO_RATE 22050
#define AUDIO_FORMAT AUDIO_S16
#define AUDIO_CHANNELS 2
#define AUDIO_BUFFERS 4096

#define DIRECTION_UP 0
#define DIRECTION_DOWN 1
#define DIRECTION_RIGHT 2
#define DIRECTION_LEFT 3

#define BODYSIZE 20

#define APPLE_SCORE 100
#define REMOVEBODYPART_SCORE 100

#define WINNER_SCORE 2500

#endif